version: '3.8'
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - frontend
    volumes:
      - ~/Desktop/data/wp:/wordpress/
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    networks:
      - frontend
      - backend
    volumes:
      - ~/Desktop/data/wp:/wordpress/
    depends_on:
      - mariadb
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - ~/Desktop/data/db:/var/lib/mysql/
    networks:
      - backend
networks:
  frontend:
    name: front_end
  backend:
    name: back_end