version: '3'
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
  #   volumes:
  #     - /wordpress:/var/nginx/html
  #   links:
  #     - wordpress
  # wordpress:
  #   build: ./requirements/wordpress
