version: '3'

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - frontend
    volumes:
      - '../../ybouali/data/website:/var/www/html'
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    networks:
      - frontend
      - backend
    volumes:
      - '../../ybouali/data/website:/var/www/html'
    depends_on:
      - mariadb
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    # volumes:
    #   - '../../ybouali/data/database:/var/lib/mysql'
    networks:
      - backend
networks:
  frontend:
  backend: