version: '3'
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./requirements/wordpress:/var/www/html
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
  