version: '3.9'
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: nginx:nginx
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - wordpress
      - react
      - adminer
      - portainer
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-wordpress:/wordpress/
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:wordpress
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - wp-wordpress:/wordpress/
    depends_on:
      - mariadb
      - redis
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - db-mariadb:/var/lib/mysql/
    networks:
      - inception
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis:redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - inception
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer:adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb
  react:
    build: ./requirements/bonus/react
    container_name: react
    image: react:react
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - inception
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    image: ftp:ftp
    restart: unless-stopped
    ports:
      - "21:21"
      - "20:20"
      - "4400-4500:4400-4500"
    networks:
      - inception
    env_file:
      - ./.env
    volumes:
      - wp-wordpress:/home/ybouali/ftp/
    depends_on:
      - wordpress
  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    image: portainer:portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    networks:
      - inception
    volumes:
      - portainer_w:/var/run/
      - portainer_db:/data/
volumes:
  db-mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/ybouali/data/db
      o:  bind
  wp-wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ybouali/data/wp
      o:  bind
  portainer_w:
    driver: local
    driver_opts:
      type: none
      device: /var/run/
      o:  bind
  portainer_db:
    driver: local
    driver_opts:
      type: none
      device: /home/ybouali/data/data/
      o:  bind
networks:
  inception:
    name: inception
