version: '3.9'
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-wordpress:/wordpress/
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - wp-wordpress:/wordpress/
    depends_on:
      - mariadb
      - redis
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - db-mariadb:/var/lib/mysql/
    networks:
      - inception
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - inception
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb
volumes:
  db-mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/ybouali/data/db
      o:  bind
  wp-wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ybouali/data/wp
      o:  bind
networks:
  inception:
    name: inception
