version: '3'
services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    env_file:
      - ./.env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /Desktop/ybouali/data
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    env_file:
      - ./.env
    ports:
      - "9000:9000"
    volumes:
      - /Desktop/ybouali/data
    depends_on:
      - mariadb
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file:
      - ./.env
    ports:
      - "3306:3306"