version: '3.9'
services:
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file:
      - ./srcs/.env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-wordpress:/wordpress/
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - ./srcs/.env
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - wp-wordpress:/wordpress/
    depends_on:
      - mariadb
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./srcs/.env
    ports:
      - "3306:3306"
    volumes:
      - db-mariadb:/var/lib/mysql/
    networks:
      - inception
volumes:
  db-mariadb:
    driver: local
    driver_opts:
      type: none
      device: ~/Desktop/data/db
      o:  bind
  wp-wordpress:
    driver: local
    driver_opts:
      type: none
      device: ~/Desktop/data/wp
      o:  bind
networks:
  inception:
    name: inception