version: '3'
services:
  nginx:
    build: ./srcs/requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file:
      - ./srcs/.env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-wordpress:/wordpress/
  wordpress:
    build: ./srcs/requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - ./srcs/.env
    ports:
      - "9000:9000"
    networks:
      - inception
    volumes:
      - wp-wordpress:/wordpress/
    depends_on:
      - mariadb
  mariadb:
    build: ./srcs/requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./srcs/.env
    ports:
      - "3306:3306"
    volumes:
      - db-mariadb:/var/lib/mysql/
    networks:
      - inception
volumes:
  db-mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o:  'bind'
      device: '~/Desktop/data/db'
  wp-wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o:  'bind'
      device: '~/Desktop/data/wp'
networks:
  inception:
    name: inception